#:schema node_modules/wrangler/config-schema.json
name = "mailman"
main = "src/index.ts"
compatibility_date = "2024-09-23"
compatibility_flags = [ "nodejs_compat" ]

send_email = [{ name = "SEB" }]

[observability]
enabled = true

[vars]
SENDER = ""
RECIPIENT = ""
